token: ${DISCORD_TOKEN}
spring:
  datasource:
    url: jdbc:postgresql://${DATASOUCE_HOST:localhost}:5432/test_db
    username: ${DATASOUCE_USER}
    password: ${DATASOUCE_PASS}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
