spring:
  datasource:
    url: jdbc:postgresql://93.170.76.21:5432/test_db
    username: raft
    password: 123456
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
