# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_ME }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS_ME }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    - run: java -version && mvn --version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: copy using rsync the packed jar
      run: scp JustBot/TestDir/JustBot.jar  ${{ secrets.SSH_USER_ME }}@${{ secrets.HOST_IP_ME }}:/root/discordtest/
    - uses: actions/upload-artifact@v2-preview
      with:
        name: JustBot
        path: JustBot/TestDir/JustBot.jar
